name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 2 * * 2'

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo ~/.moon/bin >> $GITHUB_PATH

      - name: check single file
        run: |
          find . -maxdepth 1 -type f -name '*.mbt' -not -name '018_global_mutable.mbt' | \
          while read -r file; do
            moonc check "$file" -std-path ~/.moon/lib/core/target/wasm-gc/release/bundle -is-main || exit 1
          done

      - name: check package
        run: |
          find . -maxdepth 1 -type d -not -name '.*' -not -name 'course' -not -name 'packages' -not -name 'ffi' | while read -r dir; do
            moon check -C "$dir" || exit 1
          done
