name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 2 * * 2'

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo ~/.moon/bin >> $GITHUB_PATH

      - name: check single file
        run: |
          find . -maxdepth 1 -type f -name '*.mbt' | \
          while read -r file; do
            moonc check "$file" -std-path ~/.moon/lib/core/target/wasm-gc/release/bundle || exit 1
            moonc check "$file" -std-path ~/.moon/lib/core/target/wasm/release/bundle || exit 1
            moonc check "$file" -std-path ~/.moon/lib/core/target/js/release/bundle || exit 1
          done
